managing:
  success-wizard-creation: The arena setup has been started. Please select a Postion 1 for the arena bounds. Use /minigame setpos
  success-pos1-placed: Position 1 is set. Next, please select a postion 2...
  success-pos2-placed: Position 2 is set. Next, please select a throwback block outside of the arena...
  success-outpos-placed-arena-created: Outside Block set. Creating arena...
  success-setup-canceled: Canceled creation.
  success-editing-started: You are now editing the arena. Input your new value with /minigame edit-input <value>
  success-edited-value: Value got updated. You might need to restart/refresh the arena for changes to be applied.
  success-editing-ended: You left the arena editing mode.
  error-outpos-in-bounds: Error. Please place the outside block outside of the arena.
  error-already-creating: You can't create a new arena, because the previous setup is still pending. Finish the setup or use /minigame setup-cancel
  error-unknown-gametype: The gamemode you specified is unknown.
  error-duplicate-name: An arena with that name already exists. Please choose another name.
  error-no-wizard-running: You need to start a setup with /minigame create <Gamemode> <Name> first
  error-no-permission: You don't have permission to do that.
  error-game-not-found: There's no game with that name.
  error-create-wrong-syntax: Insufficient parameters. Use /minigame create <Gamemode> <Name>
  error-edit-wrong-syntax: Insufficient parameters. Use /minigame edit <Name>
  error-game-running: You cant do this while the game is running
  error-already-editing: You are already editing an arena.
  error-not-editing: You arent editing anything at the moment.
  error-edit-illegal-value-input: 'Error while parsing input: '
game:
  success-queue-joined: 'You are queued. Your position is: '
  success-queue-left: You left the queue.
  error-already-in-queue: You are already queued up for a game.
  error-queue-closed: You can't join this game. The queue is closed.
  error-not-in-queue: You're not in a queue.
general:
  error-send-from-console: Use this command as a player.
  error-subcommand-not-found: Subcommand not found.