name: MinigameBox
version: '1.0'
main: dev.upscairs.minigameBox.MinigameBox
api-version: '1.20'
commands:
  minigame:
    ussage: /<command>
permissions:
  minigamebox:
    manage:
      description: Allows to edit and moderate games.
      default: op
