name: MinigameBox
version: '0.1.2'
main: dev.upscairs.minigameBox.MinigameBox
api-version: '1.21.1'
commands:
  minigame:
    ussage: /<command>
permissions:
  minigamebox:
    manage:
      description: Allows to edit and moderate games.
      default: op
