name: MinigameBox
version: '1.0'
main: dev.upscairs.minigameBox.MinigameBox
api-version: '1.20'
commands:
  minigame:
    ussage: /<command>
permissions:
  minigamebox:
    inqueue:
      description: Player in queue. Can't join other queues.
      default: false
    ingame:
      spleef:
        description: Player is in spleef game. Various commands blocked. Block behaviour adjusted.
        default: false
    manage:
      description: Allows to edit and moderate games.
      default: op
